# Generated by Django 6.0.5 on 2026-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non Teaching Staff'), ('PARENT', 'Parent'), ('STUDENTStudent', 'Student')], max_length=50),
        ),
    ]
