# Generated by Django 6.0.5 on 2026-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_picture_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHING_STAFF', 'Teaching Staff'), ('PARENT', 'Parent')], max_length=50),
        ),
    ]
