# Generated by Django 6.0.6 on 2026-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_backfill_receipt_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
