# Generated by Django 6.0.6 on 2026-07-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_feepayment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=50),
        ),
    ]
