# Generated by Django 6.0.6 on 2026-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_student_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['stage'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('level', 'stage')},
        ),
    ]
