# Generated by Django 6.0.6 on 2026-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_class_options_class_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
