# Generated by Django 6.0.6 on 2026-06-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_class_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='academics.class'),
        ),
    ]
