# Generated by Django 6.0.6 on 2026-06-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('JHS', 'Jhs'), ('KINDERGARTEN', 'KG'), ('LOWER_PRIMARY', 'Lower Primary'), ('UPPER_PRIMARY', 'Upper Primary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='academics.class'),
        ),
    ]
