# Generated by Django 6.0.6 on 2026-06-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_marked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.class'),
        ),
    ]
