# Generated by Django 6.0.6 on 2026-06-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_attendance_class_marked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
