# Generated by Django 6.0.6 on 2026-06-19 10:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_attendancerecord_updated_at_alter_attendance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 6, 19, 10, 4, 22, 247172, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHING_STAFF'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
