# Generated by Django 6.0.6 on 2026-06-19 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_attendance_date_alter_class_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
