# Generated by Django 6.0.6 on 2026-06-20 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_alter_class_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.OneToOneField(blank=True, limit_choices_to={'role__in': ['TEACHING_STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
