# Generated by Django 6.0.6 on 2026-06-22 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_class_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['TEACHING_STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('CLASS TEST', 'Class Test'), ('EXAM', 'Exam'), ('EXERCISE', 'Exercise')], max_length=30)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.student')),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
