# Generated by Django 6.0.6 on 2026-06-22 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_classsubject_teacher_assessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['TEACHING_STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
