# Generated by Django 6.0.6 on 2026-06-23 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_alter_assessment_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/', validators=[django.core.validators.FileExtensionValidator('.png', '.jpeg', '.jpg')]),
        ),
    ]
