# Generated by Django 6.0.6 on 2026-06-23 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpeg', '.jpg'])]),
        ),
    ]
