# Generated by Django 6.0.6 on 2026-06-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_alter_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
