# Generated by Django 6.0.6 on 2026-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('DISMISSED', 'Dismissed'), ('TRANSFERRED', 'Transferred'), ('ENROLLED', 'Enrolled')], default='ENROLLED', max_length=30),
        ),
    ]
