# Generated by Django 6.0.6 on 2026-07-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DISMISSED', 'Dismissed'), ('TRANSFERRED', 'Transferred')], default='ENROLLED', max_length=30),
        ),
    ]
