# Generated by Django 6.0.6 on 2026-08-16 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_class', to='academics.class'),
        ),
    ]
