# Generated by Django 6.0.6 on 2026-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_studentclasshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DISMISSED', 'Dismissed'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated')], default='ENROLLED', max_length=30),
        ),
    ]
